tasks1/lib/tasks1_web/router.ex
defmodule Tasks1Web.Router do
  use Tasks1Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Tasks1Web.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Tasks1Web do
    pipe_through :browser # Use the default browser stack
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Tasks1Web do
  #   pipe_through :api
  # end
end

tasks1/lib/tasks1_web/views/layout_view.ex
defmodule Tasks1Web.LayoutView do
  use Tasks1Web, :view
end

tasks1/lib/tasks1_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Tasks1 · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_url(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div id="cursor trail">
        <script language="JavaScript1.2">
		var trailLength = 8 // The length of trail (8 by default; put more for longer "tail")
		var path = "http://downloads.totallyfreecursors.com/thumbnails/bluemultiglit.gif" // URL of your image


		var standardbody=(document.compatMode=="CSS1Compat")? document.documentElement : document.body //create reference to common "body" across doctypes
		var i,d = 0

		function initTrail() { // prepares the script
			images = new Array() // prepare the image array
			for (i = 0; i < parseInt(trailLength); i++) {
				images[i] = new Image()
				images[i].src = path
			}
			storage = new Array() // prepare the storage for the coordinates
			for (i = 0; i < images.length*3; i++) {
				storage[i] = 0
			}
			for (i = 0; i < images.length; i++) { // make divs for IE and layers for Navigator
				document.write('<div id="obj' + i + '" style="position: absolute; z-Index: 100; height: 0; width: 0"><img src="' + images[i].src + '"></div>')
			}
			trail()
		}
		function trail() { // trailing function
			for (i = 0; i < images.length; i++) { // for every div/layer
				document.getElementById("obj" + i).style.top = storage[d]+'px' // the Y-coordinate
				document.getElementById("obj" + i).style.left = + storage[d+1]+'px' // the X-coordinate
				d = d+2
			}
			for (i = storage.length; i >= 2; i--) { // save the coordinate for the div/layer that's behind
				storage[i] = storage[i-2]
			}
			d = 0 // reset for future use
			var timer = setTimeout("trail()",10) // call recursively 
		}
		function processEvent(e) { // catches and processes the mousemove event 
			if (window.event) { // for IE
				storage[0] = window.event.y+standardbody.scrollTop+10
				storage[1] = window.event.x+standardbody.scrollLeft+10
			} else {
				storage[0] = e.pageY+12
				storage[1] = e.pageX+12
			}
		}

			initTrail() 
			document.onmousemove = processEvent // start capturing

		</script> 
    </div>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <div class="col-4">
          <a class="navbar-brand" href="#">Task Tracker</a>
        </div>
        <div class="col-4">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Tasks</a>
            </li>
          </ul>
        </div>
		<div class="col-4">
		  <%= if @current_user do %>
			<p class="my-3">
			  User: <%= @current_user.email %> |
			  <%= link("Logout", to: Routes.session_path(@conn, :delete),
				method: :delete) %>
			</p>
		  <% else %>
			<%= form_for @conn, Routes.session_path(@conn, :create),
					[class: "form-inline"], fn f -> %>
			  <%= text_input f, :email, class: "form-control" %>
			  <%= submit "Login", class: "btn btn-secondary" %>
			<% end %>
		  <% end %>
		</div>
      </nav>

      <div class="row">
        <div class="col-12">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert">
              <%= get_flash(@conn, :error) %>
            </p>
          <% end %>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_url(@conn, "/js/app.js") %>"></script>
  </body>
</html>